services:
  oracle-db:
    image: gvenzl/oracle-free:23-slim-faststart
    container_name: etl_local_oracle_c_name
    restart: unless-stopped
    environment:
      ORACLE_PASSWORD: "Oraclepass123!"
      APP_USER: "app_user"
      APP_USER_PASSWORD: "Userpass123!"
    ports:
      - "1523:1521"
      - "5502:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

volumes:
  oracle_data:
    name: etl_oracle_data_v_name