SET SERVEROUTPUT ON SIZE UNLIMITED; 

-- -> Taradaciuc Nicolae

-- PROIECT PL/SQL - FRAMEWORK DE DEBUGGING -> Taradaciuc Nicolae
--
-- Continut / Rezumat:
--  Pasul 0) Curata obiectele vechi, daca exista
--  Pasul 1) Creeaza o copie de test a tabelului HR.EMPLOYEES
--  Pasul 2) Creeaza tabelul DEBUG_LOG
--  Pasul 3) Creeaza pachetul DEBUG_UTILS (spec + body)
--  Pasul 4) Creeaza procedura ADJUST_SALARIES_BY_COMMISSION
--  Pasul 5) Afiseaza statusul obiectelor create
--  Pasul 6) Ruleaza un bloc de test


/*
    Observatie privind implementarea:

    Am ales ca mesajele de tip WARN si ERROR sa poata fi salvate in log chiar si atunci
    cand modul de debug este dezactivat. Desi cerinta de baza conditioneaza logarea de
    activarea debug mode-ului, aceasta adaptare a fost facuta intentionat din motive de
    securitate si diagnosticare. In opinia mea,in practica, avertismentele si erorile reprezinta
    evenimente importante, care trebuie pastrate pentru analiza incidentelor chiar si in
    afara sesiunilor de debug.

    De asemenea, testele si procedurile nu a fost testata direct pe tabelul real HR.EMPLOYEES, ci pe o
    copie de test (EMPLOYEES_COPY_FOR_TESTING). Am ales aceasta abordare deoarece un
    prototip nu trebuie testat pe date reale, pentru a evita modificarea accidentala a
    informatiilor din sistemul original. 
    
    
    
    Observatie privind partea de testare:

    Pe langa implementarea cerintelor propriu-zise, in ultima parte a scriptului
    am inclus doua teste demonstrative. Acestea au rolul de a evidentia
    functionalitatea scriptului si de a valida, in mod practic, faptul ca
    cerintele din tema au fost implementate corect.
    

    Observatie suplimentara

    Am adaugat si partea de `mask if sensitive`, desi aceasta nu era ceruta explicit. 
    Am ales sa includ aceasta functionalitate din motive de securitate, 
    pentru a preveni afisarea sau salvarea accidentala a informatiilor sensibile. 
    In opinia mea, este o masura utila in practica si completeaza implementarea printr-o 
    abordare mai sigura.    
*/


-- 0) CURATARE OBIECTE VECHI
--
-- Stergem obiectele daca au ramas din rulari anterioare.
-- Coduri tratate:
--   -4043 = object does not exist
--   -942  = table or view does not exist
--------------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE adjust_salaries_by_commission';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE debug_utils';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE debug_log PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE employees_copy_for_testing PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/



-- 1) CREAREA COPIEI DE TEST

CREATE TABLE employees_copy_for_testing AS
SELECT *
FROM HR.EMPLOYEES;
/

ALTER TABLE employees_copy_for_testing
    ADD CONSTRAINT pk_emp_copy_for_testing PRIMARY KEY (employee_id);
/


-- 2) TABELUL DE LOGARE

-- Acest tabel este baza framework-ului de debugging.
-- SESSION_ID se completeaza automat cu sesiunea Oracle curenta.

CREATE TABLE debug_log (
    log_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_time     TIMESTAMP DEFAULT SYSTIMESTAMP,
    module_name  VARCHAR2(100),
    line_no      NUMBER,
    log_level    VARCHAR2(10),
    error_code   NUMBER,
    log_message  VARCHAR2(4000),
    session_id   VARCHAR2(50) DEFAULT SYS_CONTEXT('USERENV', 'SESSIONID')
);
/

CREATE INDEX idx_debug_log_session_id ON debug_log(session_id);
/

CREATE INDEX idx_debug_log_log_time ON debug_log(log_time);
/


-- 3) SPECIFICATIA PACHETULUI DEBUG_UTILS

-- Ce contine:
--   - g_debug_mode: flag global pentru sesiunea curenta
--   - enable_debug / disable_debug
--   - log(p_module_name, p_line, p_message) -> procedura ceruta explicit in tema

--   - procedurile cerute in PDF sunt:
--         log_msg(p_message)
--         log_variable(p_name, p_value)
--         log_error(p_proc, p_err)
--   - dar eu am preferat sa le adaug si pe acestea / am preferat sa le extind 
--     functionalitatea astfel:
--         log_msg(p_module_name, p_line, p_message)
--         log_variable(p_module_name, p_line, p_name, p_value)
--         log_error(p_module_name, p_line, p_err)

--	 - Le-am "extins" deoarce astfel voi putea sa adaug in loguri si locul "real"
--     al apelului respectiv


CREATE OR REPLACE PACKAGE debug_utils AS

    -- Niveluri logare
    --
    --   - INFO  -> doar cand debug-ul este activ
    --   - WARN  -> poate ramane activ si fara debug
    --   - ERROR -> poate ramane activ si fara debug

	g_debug_mode BOOLEAN := FALSE;
    g_warn_mode  BOOLEAN := TRUE;
    g_error_mode BOOLEAN := TRUE;


    -- Activare / dezactivare mod-uri

    PROCEDURE enable_debug;
    PROCEDURE disable_debug;

    PROCEDURE enable_warn;
    PROCEDURE disable_warn;

    PROCEDURE enable_error;
    PROCEDURE disable_error;

    PROCEDURE clear_session_logs;
    PROCEDURE purge_logs;


    PROCEDURE log(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_message     IN VARCHAR2
    );


    -- Procedurile simple
    PROCEDURE log_msg(
        p_message IN VARCHAR2
    );

    PROCEDURE log_variable(
        p_name  IN VARCHAR2,
        p_value IN VARCHAR2
    );

    PROCEDURE log_warn(
        p_proc IN VARCHAR2,
        p_warn IN VARCHAR2
    );

    PROCEDURE log_error(
        p_proc IN VARCHAR2,
        p_err  IN VARCHAR2
    );

    PROCEDURE log_error(
        p_proc     IN VARCHAR2,
        p_err      IN VARCHAR2,
        p_err_code IN NUMBER
    );


    -- Procedurile extinse / Abordare personala
    PROCEDURE log_msg(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_message     IN VARCHAR2
    );

    PROCEDURE log_variable(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_name        IN VARCHAR2,
        p_value       IN VARCHAR2
    );

    PROCEDURE log_warn(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_warn        IN VARCHAR2
    );

    PROCEDURE log_error(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_err         IN VARCHAR2
    );

    PROCEDURE log_error(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_err         IN VARCHAR2,
        p_err_code    IN NUMBER
    );
END debug_utils;
/
SHOW ERRORS PACKAGE debug_utils



-- 4) BODY-UL PACHETULUI DEBUG_UTILS

CREATE OR REPLACE PACKAGE BODY debug_utils AS

    -- SANITIZE_TEXT
    --
    -- Curata textul inainte de logare:
    --   1) inlocuieste NULL cu <NULL>
    --   2) elimina newline-urile
    --   3) limiteaza textul la 4000 caractere

    FUNCTION sanitize_text(p_text IN VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        RETURN SUBSTR(
                   REPLACE(REPLACE(NVL(p_text, '<NULL>'), CHR(10), ' '), CHR(13), ' '),
                   1,
                   4000
               );
    END sanitize_text;


    -- MASK_IF_SENSITIVE
    --
    -- Daca numele variabilei pare sensibil, nu logam valoarea reala.
    -- Exemple tratate: PASS, PASSWORD, PWD, TOKEN, SECRET, API_KEY

    FUNCTION mask_if_sensitive(
        p_name  IN VARCHAR2,
        p_value IN VARCHAR2
    ) RETURN VARCHAR2 IS
        l_name VARCHAR2(4000);
    BEGIN
        l_name := UPPER(NVL(p_name, 'X'));

        IF REGEXP_LIKE(l_name, '(^|_)(PASS|PASSWORD|PWD|TOKEN|SECRET|API_KEY)(_|$)') THEN
            RETURN '[REDACTED]';
        END IF;

        RETURN sanitize_text(p_value);
    END mask_if_sensitive;

    FUNCTION detect_level_from_message(
        p_message IN VARCHAR2
    ) RETURN VARCHAR2 IS
        l_message VARCHAR2(4000) := UPPER(NVL(p_message, ''));
    BEGIN
        IF l_message LIKE '[ERROR]%' THEN
            RETURN 'ERROR';
        ELSIF l_message LIKE '[WARN]%' THEN
            RETURN 'WARN';
        ELSE
            RETURN 'INFO';
        END IF;
    END detect_level_from_message;

    FUNCTION normalize_log_level(
        p_log_level IN VARCHAR2,
        p_message   IN VARCHAR2
    ) RETURN VARCHAR2 IS
        l_log_level VARCHAR2(10);
    BEGIN
        l_log_level := UPPER(TRIM(NVL(p_log_level, detect_level_from_message(p_message))));

        IF l_log_level = 'INFO'
           OR l_log_level = 'WARN'
           OR l_log_level = 'ERROR' THEN
            RETURN l_log_level;
        END IF;

        RETURN 'INFO';
    END normalize_log_level;

    FUNCTION should_write_message(
        p_log_level IN VARCHAR2,
        p_force     IN BOOLEAN DEFAULT FALSE
    ) RETURN BOOLEAN IS
        l_level VARCHAR2(10);
    BEGIN
        IF p_force THEN
            RETURN TRUE;
        END IF;

        l_level := normalize_log_level(p_log_level, NULL);

        CASE l_level
            WHEN 'WARN' THEN
                RETURN g_warn_mode;
            WHEN 'ERROR' THEN
                RETURN g_error_mode;
            ELSE
                RETURN g_debug_mode;
        END CASE;
    END should_write_message;


    -- WRITE_LOG
    --
    -- Procedura interna care scrie efectiv in DEBUG_LOG.
    --
    -- P_FORCE = TRUE inseamna ca va scrie logul chiar daca g_debug_mode este FALSE
    --
    -- Am pus AUTONOMOUS_TRANSACTION pentru ca logurile sa ramana salvate
    -- chiar daca tranzactia principala este anulata cu ROLLBACK.

    PROCEDURE write_log(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_message     IN VARCHAR2,
        p_force       IN BOOLEAN DEFAULT FALSE,
        p_log_level   IN VARCHAR2 DEFAULT NULL,
        p_error_code  IN NUMBER DEFAULT NULL
    ) IS
        PRAGMA AUTONOMOUS_TRANSACTION;

        l_module_name debug_log.module_name%TYPE;
        l_log_message debug_log.log_message%TYPE;
        l_log_level   debug_log.log_level%TYPE;
    BEGIN
        l_log_level := normalize_log_level(p_log_level, p_message);

        IF should_write_message(l_log_level, p_force) THEN
            l_module_name := SUBSTR(NVL(p_module_name, 'UNKNOWN_MODULE'), 1, 100);
            l_log_message := sanitize_text(p_message);

            INSERT INTO debug_log (
                module_name,
                line_no,
                log_level,
                error_code,
                log_message
            )
            VALUES (
                l_module_name,
                p_line,
                l_log_level,
                p_error_code,
                l_log_message
            );

            COMMIT;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE(
                '[DEBUG_FRAMEWORK_WARNING] write_log failed. SQLCODE=' || SQLCODE ||
                ' | SQLERRM=' || SQLERRM
            );
            ROLLBACK;
    END write_log;


    -- ENABLE_DEBUG
    --
    -- Activam debug-ul si scriem un mesaj.
    PROCEDURE enable_debug IS
    BEGIN
        g_debug_mode := TRUE;

        write_log(
            $$PLSQL_UNIT,
            $$PLSQL_LINE,
            '[INFO] Debug mode enabled.',
            TRUE,
            'INFO'
        );
    END enable_debug;



    -- DISABLE_DEBUG
    --
    -- Scriem intai mesajul si apoi dezactivam debug-ul.
    PROCEDURE disable_debug IS
    BEGIN
        write_log(
            $$PLSQL_UNIT,
            $$PLSQL_LINE,
            '[INFO] Debug mode disabled.',
            TRUE,
            'INFO'
        );

        g_debug_mode := FALSE;
    END disable_debug;

    PROCEDURE enable_warn IS
    BEGIN
        g_warn_mode := TRUE;

        write_log(
            $$PLSQL_UNIT,
            $$PLSQL_LINE,
            '[INFO] WARN level enabled.',
            TRUE,
            'INFO'
        );
    END enable_warn;

    PROCEDURE disable_warn IS
    BEGIN
        write_log(
            $$PLSQL_UNIT,
            $$PLSQL_LINE,
            '[INFO] WARN level disabled.',
            TRUE,
            'INFO'
        );

        g_warn_mode := FALSE;
    END disable_warn;

    PROCEDURE enable_error IS
    BEGIN
        g_error_mode := TRUE;

        write_log(
            $$PLSQL_UNIT,
            $$PLSQL_LINE,
            '[INFO] ERROR level enabled.',
            TRUE,
            'INFO'
        );
    END enable_error;

    PROCEDURE disable_error IS
    BEGIN
        write_log(
            $$PLSQL_UNIT,
            $$PLSQL_LINE,
            '[INFO] ERROR level disabled.',
            TRUE,
            'INFO'
        );

        g_error_mode := FALSE;
    END disable_error;

    PROCEDURE clear_session_logs IS
        PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        DELETE FROM debug_log
         WHERE session_id = SYS_CONTEXT('USERENV', 'SESSIONID');

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE(
                '[DEBUG_FRAMEWORK_WARNING] clear_session_logs failed. SQLCODE=' || SQLCODE ||
                ' | SQLERRM=' || SQLERRM
            );
            ROLLBACK;
    END clear_session_logs;

    PROCEDURE purge_logs IS
        PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        DELETE FROM debug_log;

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE(
                '[DEBUG_FRAMEWORK_WARNING] purge_logs failed. SQLCODE=' || SQLCODE ||
                ' | SQLERRM=' || SQLERRM
            );
            ROLLBACK;
    END purge_logs;



    -- LOG

    PROCEDURE log(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_message     IN VARCHAR2
    ) IS
    BEGIN
        write_log(
            p_module_name,
            p_line,
            p_message
        );
    END log;


    -- LOG_MSG - varianta simpla
    --
    -- O am scrisa pentru a respecta exact logica din PDF, dar eu am partea extinsa
	-- care in opinia mea, este mai "buna"

    PROCEDURE log_msg(
        p_message IN VARCHAR2
    ) IS
    BEGIN
        write_log(
            'UNKNOWN_MODULE',
            NULL,
            '[INFO] ' || NVL(p_message, '<NULL>'),
            FALSE,
            'INFO'
        );
    END log_msg;


    -- LOG_MSG - varianta extinsa
    PROCEDURE log_msg(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_message     IN VARCHAR2
    ) IS
    BEGIN
        write_log(
            p_module_name,
            p_line,
            '[INFO] ' || NVL(p_message, '<NULL>'),
            FALSE,
            'INFO'
        );
    END log_msg;


    -- LOG_VARIABLE - varianta simpla
    PROCEDURE log_variable(
        p_name  IN VARCHAR2,
        p_value IN VARCHAR2
    ) IS
    BEGIN
        write_log(
            'UNKNOWN_MODULE',
            NULL,
            '[INFO] ' || sanitize_text(p_name) || '=' || mask_if_sensitive(p_name, p_value),
            FALSE,
            'INFO'
        );
    END log_variable;


    -- LOG_VARIABLE - varianta extinsa

    PROCEDURE log_variable(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_name        IN VARCHAR2,
        p_value       IN VARCHAR2
    ) IS
    BEGIN
        write_log(
            p_module_name,
            p_line,
            '[INFO] ' || sanitize_text(p_name) || '=' || mask_if_sensitive(p_name, p_value),
            FALSE,
            'INFO'
        );
    END log_variable;

    PROCEDURE log_warn(
        p_proc IN VARCHAR2,
        p_warn IN VARCHAR2
    ) IS
    BEGIN
        write_log(
            p_proc,
            NULL,
            '[WARN] ' || NVL(p_warn, '<NULL>'),
            FALSE,
            'WARN'
        );
    END log_warn;

    PROCEDURE log_warn(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_warn        IN VARCHAR2
    ) IS
    BEGIN
        write_log(
            p_module_name,
            p_line,
            '[WARN] ' || NVL(p_warn, '<NULL>'),
            FALSE,
            'WARN'
        );
    END log_warn;


    -- LOG_ERROR - varianta simpla

    PROCEDURE log_error(
        p_proc IN VARCHAR2,
        p_err  IN VARCHAR2
    ) IS
    BEGIN
        log_error(
            p_proc,
            p_err,
            NULL
        );
    END log_error;

    PROCEDURE log_error(
        p_proc     IN VARCHAR2,
        p_err      IN VARCHAR2,
        p_err_code IN NUMBER
    ) IS
    BEGIN
        write_log(
            p_proc,
            NULL,
            '[ERROR] ' || NVL(p_err, '<NULL>'),
            FALSE,
            'ERROR',
            p_err_code
        );
    END log_error;



    -- LOG_ERROR - varianta extinsa

    PROCEDURE log_error(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_err         IN VARCHAR2
    ) IS
    BEGIN
        log_error(
            p_module_name,
            p_line,
            p_err,
            NULL
        );
    END log_error;

    PROCEDURE log_error(
        p_module_name IN VARCHAR2,
        p_line        IN NUMBER,
        p_err         IN VARCHAR2,
        p_err_code    IN NUMBER
    ) IS
    BEGIN
        write_log(
            p_module_name,
            p_line,
            '[ERROR] ' || NVL(p_err, '<NULL>'),
            FALSE,
            'ERROR',
            p_err_code
        );
    END log_error;

END debug_utils;
/
SHOW ERRORS PACKAGE BODY debug_utils



-- 5) PROCEDURA PRINCIPALA
--
--   Pentru fiecare angajat:
--     - daca commission_pct NU este NULL -> marire cu acel procent
--     - daca commission_pct ESTE NULL    -> marire cu 2%
--
-- IMPLEMENTARE:
--   - folosim cursor explicit
--   - folosim FOR UPDATE OF salary
--   - folosim WHERE CURRENT OF pentru a actualiza exact randul curent
--   - folosim framework-ul de debug la pasii importanti:
--       citire date, calcul, actualizare

CREATE OR REPLACE PROCEDURE adjust_salaries_by_commission
IS

    -- Cursorul parcurge copia de test

    CURSOR c_employees IS
        SELECT employee_id,
               last_name,
               salary,
               commission_pct
          FROM employees_copy_for_testing
         ORDER BY employee_id
         FOR UPDATE OF salary;

    l_increase_rate NUMBER;
    l_new_salary    NUMBER;
    l_rows_updated  NUMBER;
BEGIN

    -- Ce avem aici e pe copia de test, nu pe HR.EMPLOYEES direct.
 
    debug_utils.log(
        $$PLSQL_UNIT,
        $$PLSQL_LINE,
        '[SECURITY] Procedura ruleaza doar pe EMPLOYEES_COPY_FOR_TESTING. HR.EMPLOYEES este folosit doar ca sursa pentru copiere.'
    );

    debug_utils.log_msg(
        $$PLSQL_UNIT,
        $$PLSQL_LINE,
        'Procedura de ajustare a salariilor a pornit.'
    );

    -- Parcurgem fiecare angajat.
    FOR r IN c_employees LOOP


        -- PAS 1: citim si logam datele curente

        debug_utils.log_msg(
            $$PLSQL_UNIT,
            $$PLSQL_LINE,
            'Citire date pentru angajatul curent.'
        );

        debug_utils.log_variable(
            $$PLSQL_UNIT,
            $$PLSQL_LINE,
            'employee_id',
            TO_CHAR(r.employee_id)
        );

        debug_utils.log_variable(
            $$PLSQL_UNIT,
            $$PLSQL_LINE,
            'last_name',
            r.last_name
        );

        debug_utils.log_variable(
            $$PLSQL_UNIT,
            $$PLSQL_LINE,
            'old_salary',
            TO_CHAR(r.salary, '9999999990.00')
        );

        debug_utils.log_variable(
            $$PLSQL_UNIT,
            $$PLSQL_LINE,
            'commission_pct',
            NVL(TO_CHAR(r.commission_pct), 'NULL')
        );

        IF r.commission_pct IS NOT NULL AND r.commission_pct < 0 THEN
            debug_utils.log_warn(
                $$PLSQL_UNIT,
                $$PLSQL_LINE,
                'commission_pct negativ pentru employee_id=' || r.employee_id ||
                ' (' || TO_CHAR(r.commission_pct) || '). Salariul va scadea.'
            );
        ELSIF r.commission_pct IS NOT NULL AND r.commission_pct > 0.50 THEN
            debug_utils.log_warn(
                $$PLSQL_UNIT,
                $$PLSQL_LINE,
                'commission_pct neobisnuit de mare pentru employee_id=' || r.employee_id ||
                ' (' || TO_CHAR(r.commission_pct) || '). Verifica daca valoarea este corecta.'
            );
        END IF;


        -- PAS 2: stabilim procentul de marire

        IF r.commission_pct IS NOT NULL THEN
            l_increase_rate := r.commission_pct;

            debug_utils.log_msg(
                $$PLSQL_UNIT,
                $$PLSQL_LINE,
                'commission_pct are valoare; se foloseste procentul din tabel.'
            );
        ELSE
            l_increase_rate := 0.02;

            debug_utils.log_msg(
                $$PLSQL_UNIT,
                $$PLSQL_LINE,
                'commission_pct este NULL; se foloseste marirea implicita de 2%.'
            );
        END IF;

        debug_utils.log_variable(
            $$PLSQL_UNIT,
            $$PLSQL_LINE,
            'increase_rate',
            TO_CHAR(l_increase_rate, '0.9999')
        );


        -- PAS 3: calculam noul salariu

        l_new_salary := ROUND(r.salary * (1 + l_increase_rate), 2);

        IF l_new_salary < r.salary THEN
            debug_utils.log_warn(
                $$PLSQL_UNIT,
                $$PLSQL_LINE,
                'Noul salariu este mai mic decat salariul initial pentru employee_id=' ||
                r.employee_id ||
                '. old_salary=' || TO_CHAR(r.salary, '9999999990.00') ||
                ', new_salary=' || TO_CHAR(l_new_salary, '9999999990.00')
            );
        END IF;

        debug_utils.log_msg(
            $$PLSQL_UNIT,
            $$PLSQL_LINE,
            'S-a calculat noul salariu.'
        );

        debug_utils.log_variable(
            $$PLSQL_UNIT,
            $$PLSQL_LINE,
            'new_salary',
            TO_CHAR(l_new_salary, '9999999990.00')
        );


        -- PAS 4: actualizam randul curent

        UPDATE employees_copy_for_testing
           SET salary = l_new_salary
         WHERE CURRENT OF c_employees;

        l_rows_updated := SQL%ROWCOUNT;

        debug_utils.log_msg(
            $$PLSQL_UNIT,
            $$PLSQL_LINE,
            'S-a executat instructiunea UPDATE.'
        );

        debug_utils.log_variable(
            $$PLSQL_UNIT,
            $$PLSQL_LINE,
            'rows_updated',
            TO_CHAR(l_rows_updated)
        );

  
        -- PAS 5: verificare rowcount
		
        IF l_rows_updated = 1 THEN
            debug_utils.log_msg(
                $$PLSQL_UNIT,
                $$PLSQL_LINE,
                'Actualizarea a reusit pentru angajatul curent.'
            );
        ELSE
            debug_utils.log_warn(
                $$PLSQL_UNIT,
                $$PLSQL_LINE,
                'SQL%ROWCOUNT=' || l_rows_updated ||
                ' pentru employee_id=' || r.employee_id
            );
        END IF;
    END LOOP;

    debug_utils.log_msg(
        $$PLSQL_UNIT,
        $$PLSQL_LINE,
        'Procedura de ajustare a salariilor s-a incheiat cu succes.'
    );

EXCEPTION
    WHEN OTHERS THEN

        -- Logam eroarea si backtrace-ul
		
        debug_utils.log_error(
            $$PLSQL_UNIT,
            $$PLSQL_LINE,
            SQLERRM || ' | Backtrace: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,
            SQLCODE
        );

        RAISE;
END adjust_salaries_by_commission;
/
SHOW ERRORS PROCEDURE adjust_salaries_by_commission




-- 6) MESAJ FINAL
BEGIN
    DBMS_OUTPUT.PUT_LINE('Implementarea a fost creata cu succes.');
    DBMS_OUTPUT.PUT_LINE('Tabelul de lucru este EMPLOYEES_COPY_FOR_TESTING.');
END;
/



-- 7) BLOC DE TEST
--
-- Ce demonstram aici:
--   TEST 1 - debug activ:
--       - se modifica salariile in copia de test
--       - se scriu loguri
--       - apoi modificarea salariala se anuleaza cu ROLLBACK TO SAVEPOINT
--
--   TEST 2 - debug dezactivat:
--       - procedura ruleaza
--       - logurile normale nu se mai scriu
--       - apoi anulam si aceasta rulare
--------------------------------------------------------------------------------
SET SERVEROUTPUT ON SIZE UNLIMITED;

DECLARE
    l_log_count_before NUMBER;
    l_log_count_after  NUMBER;

    ----------------------------------------------------------------------------
    -- Afisam primele 5 randuri pentru comparatie.
    ----------------------------------------------------------------------------
    PROCEDURE print_first_rows(p_title IN VARCHAR2) IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE(CHR(10) || p_title);

        FOR r IN (
            SELECT employee_id,
                   last_name,
                   salary,
                   commission_pct
              FROM (
                    SELECT employee_id,
                           last_name,
                           salary,
                           commission_pct
                      FROM employees_copy_for_testing
                     ORDER BY employee_id
                   )
             WHERE ROWNUM <= 5
        ) LOOP
            DBMS_OUTPUT.PUT_LINE(
                'ID=' || r.employee_id ||
                ' | LAST_NAME=' || r.last_name ||
                ' | SALARY=' || TO_CHAR(r.salary, '9999990.00') ||
                ' | COMMISSION_PCT=' || NVL(TO_CHAR(r.commission_pct), 'NULL')
            );
        END LOOP;
    END print_first_rows;

BEGIN
    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE('TEST 1 - DEBUG ACTIV');
    DBMS_OUTPUT.PUT_LINE('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~');
    
    -- Adaug diverse informatii pentru a adauga "diversitate" in datele de test
    
    UPDATE employees_copy_for_testing
    SET commission_pct = 0.10
    WHERE employee_id = 100;

    UPDATE employees_copy_for_testing
    SET commission_pct = 0.05
    WHERE employee_id = 101;

    UPDATE employees_copy_for_testing
    SET commission_pct = 0.9
    WHERE employee_id = 103;

    print_first_rows('Primele 5 salarii INAINTE de rulare:');

    SAVEPOINT before_test_debug_on;


    -- Activam debug-ul.

    debug_utils.enable_debug;

    SELECT COUNT(*)
      INTO l_log_count_before
      FROM debug_log;

     
    -- Rulam procedura principala.

    adjust_salaries_by_commission;

    DECLARE
        l_dummy NUMBER;
    BEGIN
        l_dummy := 1 / 0;
    EXCEPTION
        WHEN OTHERS THEN
            debug_utils.log_error(
                $$PLSQL_UNIT,
                $$PLSQL_LINE,
                'Test controlat pentru pentru a afisa functionalitatea lui log_error: ' || SQLERRM ||
                ' | Backtrace: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,
                SQLCODE
            );

            DBMS_OUTPUT.PUT_LINE('Am generat o eroare controlata pentru a testa log_error.');
    END;
    
    

    print_first_rows('Primele 5 salarii DUPA rularea procedurii de modificare a salariilor');


    -- Verificam numarul de loguri noi.
    

    SELECT COUNT(*)
      INTO l_log_count_after
      FROM debug_log;

    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE('Loguri noi create cu debug activ: ' ||
        (l_log_count_after - l_log_count_before)
    );

    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE('Ultimele 15 loguri:');

    FOR r IN (
        SELECT log_id,
               TO_CHAR(log_time, 'YYYY-MM-DD HH24:MI:SS') AS log_time_txt,
               module_name,
               line_no,
               log_level,
               error_code,
               log_message
          FROM (
                SELECT log_id,
                       log_time,
                       module_name,
                       line_no,
                       log_level,
                       error_code,
                       log_message
                  FROM debug_log
                 ORDER BY log_id DESC
               )
         WHERE ROWNUM <= 15
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(
            '#' || r.log_id ||
            ' | ' || r.log_time_txt ||
            ' | ' || r.module_name ||
            ' | LINE=' || NVL(TO_CHAR(r.line_no), 'NULL') ||
            ' | LEVEL=' || NVL(r.log_level, 'NULL') ||
            ' | ERROR_CODE=' || NVL(TO_CHAR(r.error_code), 'NULL') ||
            ' | ' || r.log_message
        );
    END LOOP;

 
    -- Anulam modificarile salariale, dar logurile raman.

    ROLLBACK TO before_test_debug_on;

    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE('Vom anula modificarile facute cu primul test printr-un ROLLBACK.');
    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE('Logurile au ramas salvate in DEBUG_LOG, deoarece folosim AUTONOMOUS_TRANSACTION.');

    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE('TEST 2 - DEBUG DEZACTIVAT');
    DBMS_OUTPUT.PUT_LINE('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~');

    SAVEPOINT before_test_debug_off;

    UPDATE employees_copy_for_testing
       SET commission_pct = -0.10
     WHERE employee_id = 100;

    UPDATE employees_copy_for_testing
       SET commission_pct = 0.75
     WHERE employee_id = 101;




    -- Dezactivam debug-ul.
    -- Mesajul de dezactivare se logheaza
    debug_utils.disable_debug;
    debug_utils.enable_warn;
    debug_utils.enable_error;

    SELECT COUNT(*)
      INTO l_log_count_before
      FROM debug_log
     WHERE log_level IN ('WARN', 'ERROR');


    -- Rulam din nou procedura fara debug activ.

    adjust_salaries_by_commission;

    SELECT COUNT(*)
      INTO l_log_count_after
      FROM debug_log
     WHERE log_level IN ('WARN', 'ERROR');


    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE(
        'Loguri WARN/ERROR create cu debug dezactivat: ' ||
        (l_log_count_after - l_log_count_before)
    );
    
    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE('Ultimele 20 loguri WARN/ERROR:');

    FOR r IN (
        SELECT log_id,
               TO_CHAR(log_time, 'YYYY-MM-DD HH24:MI:SS') AS log_time_txt,
               module_name,
               line_no,
               log_level,
               error_code,
               log_message
          FROM (
                SELECT log_id,
                       log_time,
                       module_name,
                       line_no,
                       log_level,
                       error_code,
                       log_message
                  FROM debug_log
                 WHERE log_level IN ('WARN', 'ERROR')
                 ORDER BY log_id DESC
               )
         WHERE ROWNUM <= 20
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(
            '#' || r.log_id ||
            ' | ' || r.log_time_txt ||
            ' | ' || r.module_name ||
            ' | LINE=' || NVL(TO_CHAR(r.line_no), 'NULL') ||
            ' | LEVEL=' || NVL(r.log_level, 'NULL') ||
            ' | ERROR_CODE=' || NVL(TO_CHAR(r.error_code), 'NULL') ||
            ' | ' || r.log_message
        );
    END LOOP;

    ROLLBACK TO before_test_debug_off;

    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE('Vom anula modificarile facute cu al doilea test printr-un ROLLBACK.');

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('A aparut o eroare in blocul de test: ' || SQLERRM);
        RAISE;
END;
/